/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */
rootProject.name = "cola-demo-parent"
include(":cola-demo-api")
include(":cola-demo-app")
include(":cola-demo-batch")
include(":cola-demo-joblay")
include(":cola-demo-business")
include(":cola-demo-configure")
include(":cola-demo-domain")
include(":cola-demo-infrastructure")
include(":cola-demo-common")
