/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.agmtopy.demo.java-conventions")
}

dependencies {
    implementation(project(":cola-demo-api"))
    implementation("com.alibaba.cola:cola-component-domain-starter:4.3.1")
    implementation("com.alibaba.cola:cola-component-exception:4.3.1")
}

description = "cola-demo-domain"
