/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.agmtopy.demo.java-conventions")
}

val colaVersion = "4.3.1"

dependencies {
    implementation(project(":cola-demo-business"))
    implementation(project(":cola-demo-api"))

    implementation("com.alibaba.cola:cola-component-dto:$colaVersion")
    implementation("org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.2")
    implementation("org.springframework.boot:spring-boot-starter-web:2.7.2")
    implementation("org.springframework.boot:spring-boot-starter:2.7.2")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.2")
}

description = ":cola-demo-batch"
