/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.agmtopy.demo.java-conventions")
}

dependencies {
    implementation(project(":cola-demo-domain"))
    implementation("org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.2")
    implementation("mysql:mysql-connector-java:8.0.29")
    implementation("com.alibaba:fastjson:1.2.83")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.2")
}

description = "cola-demo-infrastructure"
