/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.agmtopy.demo.java-conventions")
}

dependencies {
    implementation("com.alibaba.cola:cola-component-dto:4.3.1")
    implementation("javax.validation:validation-api:2.0.1.Final")
}

description = "cola-demo-api"
